version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: gym-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: gym-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/gymApp
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: gym-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data: